var BadgeStyle;
(function (BadgeStyle) {
    BadgeStyle[BadgeStyle["None"] = 0] = "None";
    BadgeStyle[BadgeStyle["BronzeMedal"] = 1] = "BronzeMedal";
    BadgeStyle[BadgeStyle["GoldMedal"] = 2] = "GoldMedal";
    BadgeStyle[BadgeStyle["SilverMedal"] = 3] = "SilverMedal";
    BadgeStyle[BadgeStyle["Alert"] = 4] = "Alert";
    BadgeStyle[BadgeStyle["Crown"] = 5] = "Crown";
    BadgeStyle[BadgeStyle["Ammo"] = 6] = "Ammo";
    BadgeStyle[BadgeStyle["Armour"] = 7] = "Armour";
    BadgeStyle[BadgeStyle["Barber"] = 8] = "Barber";
    BadgeStyle[BadgeStyle["Clothes"] = 9] = "Clothes";
    BadgeStyle[BadgeStyle["Franklin"] = 10] = "Franklin";
    BadgeStyle[BadgeStyle["Bike"] = 11] = "Bike";
    BadgeStyle[BadgeStyle["Car"] = 12] = "Car";
    BadgeStyle[BadgeStyle["Gun"] = 13] = "Gun";
    BadgeStyle[BadgeStyle["Heart"] = 14] = "Heart";
    BadgeStyle[BadgeStyle["Makeup"] = 15] = "Makeup";
    BadgeStyle[BadgeStyle["Mask"] = 16] = "Mask";
    BadgeStyle[BadgeStyle["Michael"] = 17] = "Michael";
    BadgeStyle[BadgeStyle["Star"] = 18] = "Star";
    BadgeStyle[BadgeStyle["Tatoo"] = 19] = "Tatoo";
    BadgeStyle[BadgeStyle["Trevor"] = 20] = "Trevor";
    BadgeStyle[BadgeStyle["Lock"] = 21] = "Lock";
    BadgeStyle[BadgeStyle["Tick"] = 22] = "Tick";
})(BadgeStyle || (BadgeStyle = {}));
export default BadgeStyle;
